# Generated by Django 3.2.9 on 2022-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='XAICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=255)),
                ('xai_algorithm', models.CharField(max_length=255)),
                ('viewData', models.JSONField()),
            ],
        ),
    ]
