# Generated by Django 3.2.9 on 2022-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='dataset',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.TextField(),
        ),
    ]
