# Generated by Django 3.2.9 on 2022-07-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220608_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=255)),
                ('rating1', models.IntegerField()),
                ('rating2', models.IntegerField()),
                ('rating3', models.IntegerField()),
                ('rating4', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
